longlian:
  datasource:
    type: sqlite
  cache:
    type: local

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:./data/longlian.db
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
