spring:
  application:
    name: "longlian-oa"
  profiles:
    active: dev          # 根据部署环境动态切换（如dev/sit/prod）
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: ${longlian.datasource.driver-class-name}
    url: jdbc:mysql://${longlian.datasource.host}:${longlian.datasource.port}/${longlian.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${longlian.datasource.username}
    password: ${longlian.datasource.password}
  data:
    redis:
      host: ${longlian.redis.host}
      port: ${longlian.redis.port}
      password: ${longlian.redis.password}
      database: ${longlian.redis.database}
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
# Swagger默认关闭，由各环境配置决定是否开启
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    enabled: false  # 默认关闭
  packages-to-scan: online.longlian.app.controller
  api-docs:
    enabled: false  # 默认关闭