longlian:
  datasource:
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
    host: ${DB_HOST}
    port: ${DB_PORT}
    database: ${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    database: ${REDIS_DATABASE:1}
cache:
  type: redis
# 测试环境调试开关关闭
debug: false
# 测试环境开启Swagger（和dev一致）
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true