longlian:
  datasource:
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
    host: ${DB_HOST}
    port: ${DB_PORT}
    database: ${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    database: ${REDIS_DATABASE:1}
cache:
  type: redis
# 生产环境关闭调试、关闭Swagger
debug: false
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false