longlian:
  datasource:
    type: mysql
  cache:
    type: redis

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_DATABASE:1}


# 测试环境调试开关关闭
debug: false
# 测试环境开启Swagger（和dev一致）
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true