longlian:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 192.168.75.131
    port: 3306
    database: longlian
    username: root
    password: 3516
  redis:
    host: 192.168.75.131
    port: 6379
    password: 3516
    database: 1